services:
  - type: web
    name: alsami-workshop-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
